version: '3.7'

services:
  database:
    container_name: postgres
    image: 'postgres'
    #    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=keltidor
        - POSTGRES_PASSWORD=Gg4dhg8fb
        - POSTGRES_DB=postgres

  app:
    build: .
    links:
      - database
    #    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/postgres
    depends_on:
      - database